### PR TITLE
Add strongswan restart service.

### PR DESCRIPTION
**Pull request by saicharansunkara-ibm**
This adds functionality to restart strongswan service at boot.

### CODE REVIEW

**Review by riddhi-ibm — APPROVED** [review]

**Comment by saicharansunkara-ibm** [comment]
The mount helper utility will now suggest to restart strongswan service if it detects a connection timeout error.
```
Debug - RunCmd: MountCmd (mount -t nfs4 -o sec=sys,nfsvers=4.1,rw 10.250.129.54:/666e7509_3577_4412_9b89_9e83a1551057 /root/test)
Error - RunCmd Failed: ExitCode(32) StdError(mount.nfs4: Connection timed out) Cmd(mount -t nfs4 -o sec=sys,nfsvers=4.1,rw 10.250.129.54:/666e7509_3577_4412_9b89_9e83a1551057 /root/test)
Error - Mount command timed out. Try to restart StrongSwan service.
Error - Share mount failed.
root@ubuntu-test:~#
```

**Review by prankulmahajan — CHANGES_REQUESTED** [review]
`remove_strongswan_restart_service` must be called in Ubuntu setup as well

**Comment by prankulmahajan** [comment]
Still I dont see new service available in system. Can you please verify once in VSI also? Thanks

**Comment by saicharansunkara-ibm** [comment]
Hi Prankul. Yes I was able to fix that and running the tests now. Will update the results soon.

**Comment by prankulmahajan** [comment]
Hi @saicharansunkara-ibm , can you please resolve the conflicts?

**Comment by prankulmahajan** [comment]
@saicharansunkara-ibm I see even after the mount.ibmshare is uninstalled, the service is not getting cleanup up from the cluster, is it possible to fix it?

**Comment by saicharansunkara-ibm** [comment]
Hi @prankulmahajan, It should be fixed now. We were using the same condition as before for the removal of service which was working for VPC.

**Review by prankulmahajan — APPROVED** [review]
Tested, looks good now

**Review by anand-desai — APPROVED** [review]

**Pull request merged**
